version: "3"

dotenv: [ "Taskfile.iac.env" ]

vars:
  AWS_REGION: ap-northeast-1

includes:
  infra:
    taskfile: ./healthcare.io.infra/taskfile.yml
    dir: ./healthcare.io.infra
  transcriber:
    taskfile: ./healthcare.io.transcriber/taskfile.yml
    dir: ./healthcare.io.transcriber
  transcribe-summary:
    taskfile: ./healthcare.io.transcribe-summary/taskfile.yml
    dir: ./healthcare.io.transcribe-summary
  chatbot:
    taskfile: ./healthcare.io.chatbot/taskfile.yml
    dir: ./healthcare.io.chatbot
  ui:
    taskfile: ./healthcare.io.ui/taskfile.yml
    dir: ./healthcare.io.ui


tasks:
  infra-up:
    cmds:
      - task: infra:up
    desc: "[cloud] 啟動基礎設施"
  infra-down:
    cmds:
      - task: infra:down
    desc: "[cloud] 停止基礎設施"
  download-mock-speech:
    cmds:
      - task: transcriber:download-mock-speech
    desc: "[cloud] 透過AWS Polly下載模擬音檔"
  deploy-transcriber:
    cmds:
      - dotnet build
      - task: transcriber:deploy
    desc: "[cloud] 打包Image並上傳到ECR (transcriber)"
  deploy-summary:
    cmds:
      - dotnet build
      - task: transcribe-summary:deploy
    desc: "[cloud] 打包Image並上傳到ECR (transcriber-summary)"
  deploy-chatbot:
    cmds:
      - dotnet build
      - task: chatbot:deploy
    desc: "[cloud] 打包Image並上傳到ECR (chatbot)"
  local-frontend-run:
    cmds:
      - task: ui:local-run
    desc: "[local] 執行angular 專案，並開啟 devtunnel 連線"
  local-frontend-down:
    cmds:
      - task: ui:local-down
    desc: "[local] 停止 angular 專案，並關閉 devtunnel 連線"
