version: "3"


tasks:
  deploy:
    internal : true
    cmds:
      - aws ecr get-login-password --region {{.AWS_REGION}} | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.{{.AWS_REGION}}.amazonaws.com
      - docker build --force-rm -t healthcarechatbot .
      - docker tag healthcarechatbot:latest $ECR_CHATBOT_URL:latest
      - docker push $ECR_CHATBOT_URL:latest
      - AWS_PAGER=""  aws lambda update-function-code --function-name $LAMBDA_CHATBOT_ARN --image-uri $ECR_CHATBOT_URL:latest --region {{.AWS_REGION}}

    desc: "[cloud] 打包Image並上傳到ECR"